### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by cawk** [BedTheGod/ConfuserEx-Unpacker-Dynamic#1]
Do you mind removing the mutations folder please as this is my work and you had no permission to post this publically

**Comment by cawk** [comment]
If you would rather discuss this privately contact me at cawkre@gmail.com

**Comment by BedTheGod** [comment]
I removed it, sorry about that. Thought it would be helpful for people.

**Comment by cawk** [comment]
Thank you, this is leaked code from a private project which I’m sure you’re aware of 
Regards
Cawk
